{{- if .Values.unsupported.privateEndpointsOverride.enabled }}
{{- $privateEndpointsURL := include "okteto.privateEndpoints" . -}}
{{- $ingressAPIVersion := include "okteto.ingress.apiVersion" . -}}
apiVersion: {{ $ingressAPIVersion }}
kind: Ingress
metadata:
  name: {{ include "okteto.fullname" . }}-private-endpoints
  labels:
    app.kubernetes.io/name: {{ include "okteto.fullname" . }}-private-endpoints
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/component: "private-endpoints"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ $privateEndpointsURL }}
    secretName: {{ .Values.wildcardCertificate.name }}
  rules:
    - host: {{ $privateEndpointsURL }}
      http:
        paths:
          - path: "/"
            {{- if eq $ingressAPIVersion "networking.k8s.io/v1" }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if eq $ingressAPIVersion "networking.k8s.io/v1" }}
              service:
                name: {{ include "okteto.fullname" . }}-private-endpoints
                port:
                  number: {{ .Values.unsupported.privateEndpointsOverride.port }}
              {{- else }}
              serviceName: {{ include "okteto.fullname" . }}-private-endpoints
              servicePort: {{ .Values.unsupported.privateEndpointsOverride.port }}
              {{- end }}
{{- end }}
